### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by vaclavkanera** [shovon8/vmware-autostart#2]
Downloaded files from Git this repository - getting this error :

● vmware-autostart.service - Automatically Start VMware Virtual Machine
     Loaded: loaded (/etc/systemd/system/vmware-autostart.service; enabled; vendor preset: enabled)
     Active: active (exited) since Wed 2022-04-06 23:40:45 CEST; 5min ago
    Process: 10197 ExecStart=/opt/vmware-autostart/bin/autostart start (code=exited, status=0/SUCCESS)
   Main PID: 10197 (code=exited, status=0/SUCCESS)

dub 06 23:40:45 chiaminer01 systemd[1]: Starting Automatically Start VMware Virtual Machine...
dub 06 23:40:45 chiaminer01 autostart[10201]: parse error: Expected another array element at line 8, column 3
dub 06 23:40:45 chiaminer01 autostart[10197]: /opt/vmware-autostart/bin/autostart: line 47: ((: counter < : syntax error: operand expected (error token is "< ")
dub 06 23:40:45 chiaminer01 systemd[1]: Finished Automatically Start VMware Virtual Machine.

**Comment by shovon8** [comment]
Did you check the `config.json` file for any syntax errors?

**Comment by vaclavkanera** [comment]
Looks like there was error in config file, I created new one and now it´s working

**Comment by bill-zhanxg** [comment]
Please close this issue, it's triggering!

**Comment by shovon8** [comment]
Closing the issue. Thanks :-)
